export enum ClientEvents {
  AUTHENTICATE = 'authenticate',
  ROOM_JOIN = 'room:join',
  ROOM_LEAVE = 'room:leave',
  SHEET_PURCHASE = 'sheet:purchase',
  PLAYER_SET_READY = 'player:set-ready',
  GAME_START = 'game:start',
  GAME_CALL_NUMBER = 'game:call-number',
  GAME_TOGGLE_AUTO_CALL = 'game:toggle-auto-call',
  GAME_RESET = 'game:reset',
  TICKET_MARK_CELL = 'ticket:mark-cell',
  TICKET_UNMARK_CELL = 'ticket:unmark-cell',
  KINH_CLAIM = 'kinh:claim',
  KINH_APPROVE = 'kinh:approve',
  KINH_REJECT = 'kinh:reject',
  KINH_START_CHALLENGE = 'kinh:start-challenge',
  CHALLENGE_PICK_CARD = 'challenge:pick-card',
}

export enum ServerEvents {
  AUTHENTICATED = 'authenticated',
  ROOM_JOINED = 'room:joined',
  ROOM_PLAYER_JOINED = 'room:player-joined',
  ROOM_PLAYER_LEFT = 'room:player-left',
  ROOM_UPDATED = 'room:updated',
  SHEET_PURCHASED = 'sheet:purchased',
  SHEET_TAKEN = 'sheet:taken',
  SHEET_PURCHASE_FAILED = 'sheet:purchase-failed',
  PLAYER_READY_CHANGED = 'player:ready-changed',
  GAME_STARTED = 'game:started',
  GAME_NUMBER_CALLED = 'game:number-called',
  GAME_PAUSED = 'game:paused',
  GAME_RESUMED = 'game:resumed',
  GAME_ENDED = 'game:ended',
  KINH_CLAIMS_UPDATED = 'kinh:claims-updated',
  KINH_VERIFY_REQUEST = 'kinh:verify-request',
  KINH_WINNER_ANNOUNCEMENT = 'kinh:winner-announcement',
  KINH_YOU_WON = 'kinh:you-won',
  KINH_REJECTED_YOU = 'kinh:rejected-you',
  KINH_REJECTED = 'kinh:rejected',
  CHALLENGE_STARTED = 'challenge:started',
  CHALLENGE_CARD_PICKED = 'challenge:card-picked',
  CHALLENGE_YOUR_PICK = 'challenge:your-pick',
  CHALLENGE_RESULT = 'challenge:result',
  PLAYER_NEAR_WIN = 'player:near-win',
  PAYMENT_REQUIRED = 'payment:required',
  ERROR = 'error',
}
